services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: police_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE: http://127.0.0.1:8000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - web

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: police_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
