# Generated by Django 4.2.11 on 2026-01-25 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('complaint', 'Complaint'), ('field_report', 'Field report')], max_length=20)),
                ('severity', models.CharField(choices=[('level_3', 'Level 3 (minor)'), ('level_2', 'Level 2 (medium)'), ('level_1', 'Level 1 (major)'), ('critical', 'Critical')], default='level_3', max_length=12)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('active', 'Active'), ('in_progress', 'In progress'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending_approval', max_length=20)),
                ('status_note', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('testimony', 'Testimony'), ('forensic', 'Forensic'), ('vehicle', 'Vehicle'), ('id_document', 'ID Document'), ('generic', 'Generic')], default='generic', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('status_note', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='cases.case')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences_recorded', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('officer_rejected', 'Officer rejected'), ('sent_to_detective', 'Sent to detective'), ('detective_rejected', 'Detective rejected'), ('approved', 'Approved'), ('rewarded', 'Reward paid')], default='pending', max_length=20)),
                ('reward_code', models.CharField(blank=True, default='', max_length=64, unique=True)),
                ('reward_amount', models.BigIntegerField(default=0)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='cases.case')),
                ('detective_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips_detective_reviewed', to=settings.AUTH_USER_MODEL)),
                ('officer_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips_officer_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='evidence/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.evidence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetectiveBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='cases.case')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('cadet_review', 'Cadet Review'), ('returned_to_complainant', 'Returned to complainant'), ('officer_review', 'Officer Review'), ('returned_to_cadet', 'Returned to cadet'), ('accepted', 'Accepted'), ('voided', 'Voided')], default='submitted', max_length=32)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('complainant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='cases.person')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_cadet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadet_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('complainant', 'Complainant'), ('witness', 'Witness'), ('suspect', 'Suspect'), ('criminal', 'Criminal'), ('judge', 'Judge'), ('detective', 'Detective'), ('sergeant', 'Sergeant'), ('captain', 'Captain'), ('chief', 'Chief'), ('coroner', 'Coroner'), ('officer', 'Officer'), ('cadet', 'Cadet')], max_length=20)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_participants', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='cases.case')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_participations', to='cases.person')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='complaint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case', to='cases.complaint'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_supervising', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BoardNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('color', models.CharField(default='#f59e0b', max_length=20)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.detectiveboard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cases.detectiveboard')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='cases.boardnote')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='cases.boardnote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BailPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bail_payments', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bail_created', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bail_payments', to='cases.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PursuitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('wanted', 'Wanted'), ('high_alert', 'High alert'), ('captured', 'Captured'), ('trial', 'Trial'), ('closed', 'Closed')], default='wanted', max_length=20)),
                ('pursuit_started_at', models.DateField(default=django.utils.timezone.now)),
                ('severity_at_report', models.CharField(choices=[('level_3', 'Level 3 (minor)'), ('level_2', 'Level 2 (medium)'), ('level_1', 'Level 1 (major)'), ('critical', 'Critical')], default='level_3', max_length=12)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pursuits', to='cases.case')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pursuits', to='cases.person')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='cases_pursu_status_66ca00_idx')],
                'unique_together': {('case', 'suspect')},
            },
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['type'], name='cases_evide_type_223339_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['status'], name='cases_evide_status_1d8f58_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='cases_compl_status_5b03bd_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['attempts'], name='cases_compl_attempt_00c65c_idx'),
        ),
        migrations.AddIndex(
            model_name='caseparticipant',
            index=models.Index(fields=['role'], name='cases_casep_role_02f18e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caseparticipant',
            unique_together={('case', 'person', 'role')},
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['number'], name='cases_case_number_a38bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['severity'], name='cases_case_severit_89f317_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'),
        ),
    ]
