# Generated by Django 4.2.11 on 2026-01-25 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailpayment',
            name='payment_type',
            field=models.CharField(choices=[('bail', 'Bail'), ('fine', 'Fine')], default='bail', max_length=10),
        ),
        migrations.AddField(
            model_name='bailpayment',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pursuitstatus',
            name='high_alert_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending approval'), ('active', 'Active'), ('in_progress', 'In progress'), ('in_trial', 'In trial'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending_approval', max_length=20),
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verdict', models.CharField(choices=[('guilty', 'Guilty'), ('not_guilty', 'Not guilty')], max_length=20)),
                ('sentence_title', models.CharField(blank=True, default='', max_length=255)),
                ('sentence_description', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='cases.case')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trials', to='cases.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, default='', max_length=100)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('message', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuspectEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detective_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sergeant_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('captain_decision', models.CharField(blank=True, default='', max_length=20)),
                ('chief_decision', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_evaluations', to='cases.case')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_evaluations', to='cases.person')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='cases_suspe_status_5bedbd_idx')],
                'unique_together': {('case', 'suspect')},
            },
        ),
    ]
