# Generated by Django 4.2.11 on 2026-01-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_complaint_complainant_and_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='complaintcomplainant',
            new_name='cases_compl_status_fe0851_idx',
            old_name='cases_compl_status_1ccf8e_idx',
        ),
    ]
