# Generated by Django 4.2.11 on 2026-01-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_rename_cases_compl_status_1ccf8e_idx_cases_compl_status_fe0851_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='approval_stage',
            field=models.CharField(choices=[('detective', 'Detective'), ('sergeant', 'Sergeant'), ('captain', 'Captain'), ('chief', 'Chief'), ('final', 'Final')], default='detective', max_length=20),
        ),
    ]
