# Generated by Django 4.2.11 on 2026-01-30 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0005_case_approval_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('level_3', 'Level 3 (minor)'), ('level_2', 'Level 2 (medium)'), ('level_1', 'Level 1 (major)'), ('critical', 'Critical')], default='level_3', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_stage', models.CharField(choices=[('detective', 'Detective'), ('sergeant', 'Sergeant'), ('captain', 'Captain')], default='detective', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_reports_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending approval'), ('active', 'Active'), ('detective_followup', 'Detective follow-up'), ('captain_review', 'Captain review'), ('chief_review', 'Chief review'), ('in_progress', 'In progress'), ('in_trial', 'In trial'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending_approval', max_length=20),
        ),
        migrations.CreateModel(
            name='FieldReportWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_report_witnesses', to='cases.person')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='cases.fieldreport')),
            ],
            options={
                'unique_together': {('report', 'person')},
            },
        ),
        migrations.AddIndex(
            model_name='fieldreport',
            index=models.Index(fields=['number'], name='cases_field_number_bfc38b_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldreport',
            index=models.Index(fields=['severity'], name='cases_field_severit_bbd40f_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldreport',
            index=models.Index(fields=['status'], name='cases_field_status_e035da_idx'),
        ),
    ]
