# Generated by Django 4.2.11 on 2026-01-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_merge_case_status_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspectevaluation',
            name='judge_verdict',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='suspectevaluation',
            name='judged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspectevaluation',
            name='sentence_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='suspectevaluation',
            name='sentence_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
