# Generated by Django 4.2.11 on 2026-02-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_add_judge_verdict_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='suspect_national_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tip',
            name='reward_code',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
