# Generated by Django 4.2.11 on 2026-02-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_case_payment_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailpayment',
            name='gateway',
            field=models.CharField(choices=[('idpay', 'IDPay'), ('zarinpal', 'Zarinpal')], default='idpay', max_length=20),
        ),
    ]
