# Generated by Django 4.2.11 on 2026-02-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_alter_bailpayment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailpayment',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('idpay', 'IDPay'), ('zarinpal', 'Zarinpal')], default='stripe', max_length=20),
        ),
    ]
