# Generated by Django 4.2.11 on 2026-02-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_alter_bailpayment_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardnote',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_notes', to='cases.evidence'),
        ),
    ]
