# Generated by Django 4.2.11 on 2026-02-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_boardnote_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectiveboard',
            name='background_color',
            field=models.CharField(default='#2a2018', max_length=20),
        ),
    ]
