# Generated by Django 4.2.11 on 2026-02-12 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0015_detectiveboard_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintcomplainant',
            name='cadet_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaintcomplainant',
            name='officer_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='complaintcomplainant',
            name='officer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='complaintcomplainant',
            name='reviewed_by_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complainant_officer_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaintcomplainant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='complaintcomplainant',
            index=models.Index(fields=['officer_status'], name='cases_compl_officer_ee836e_idx'),
        ),
    ]
