# Generated by Django 4.2.11 on 2026-02-13 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0016_complaint_complainant_officer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseComplainantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='pending', max_length=20)),
                ('cadet_attempts', models.PositiveSmallIntegerField(default=0)),
                ('officer_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('officer_rejection_reason', models.TextField(blank=True, default='')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_complainants_added', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainant_reviews', to='cases.case')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_complainant_reviews', to='cases.person')),
                ('reviewed_by_cadet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_complainants_cadet_reviewed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_complainants_officer_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='cases_casec_status_fa8e33_idx'), models.Index(fields=['officer_status'], name='cases_casec_officer_ed7144_idx')],
                'unique_together': {('case', 'person')},
            },
        ),
    ]
