# Generated by Django 4.2.11 on 2026-02-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_casecomplainantreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspectevaluation',
            name='captain_bail_decision',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='suspectevaluation',
            name='captain_bail_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
