# Generated by Django 4.2.11 on 2026-02-23 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_suspectevaluation_captain_bail_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='cases.case'),
        ),
    ]
